spring:
  application:
    name: warehouse-data-ingestion-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Logging configuration
logging:
  level:
    com.ikea.warehouse_data_ingestion_service: INFO
    org.springframework.web.multipart: DEBUG
