# Development Environment Configuration
spring:
  profiles:
    include: logging, management, kafka

# Development-specific overrides
logging:
  level:
    com.ikea.warehouse_data_ingestion_service: DEBUG
    org.springframework.kafka: DEBUG
  file:
    name: logs/warehouse-ingestion-dev.log

kafka:
  bootstrap-servers: localhost:9092
  topic: warehouse-events-dev
  producer:
    retries: 1
    batch-size: 1024
    linger-ms: 0
    acks: 1
    enable-idempotence: false
  consumer:
    group-id: warehouse-ingestion-dev-group
    auto-offset-reset: latest
    enable-auto-commit: true

server:
  port: 8080
