spring:
  application:
    name: warehouse-data-ingestion-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Logging configuration
logging:
  level:
    com.ikea.warehouse_data_ingestion_service: INFO
    org.springframework.web.multipart: DEBUG
    org.springframework.kafka: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] [%X{operation:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-}] [%X{operation:-}] %logger{50} - %msg%n"
  file:
    name: logs/warehouse-ingestion.log

# Management and monitoring endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

kafka:
  bootstrap-servers: localhost:9092
  topic: warehouse-events

