# Default/Common Configuration
spring:
  application:
    name: warehouse-data-ingestion-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
  profiles:
    active: default,logging,management,kafka,otel

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Application Information
info:
  app:
    name: ${spring.application.name}
    description: Warehouse Data Ingestion Service for IKEA
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
