# Logging Configuration Profile
logging:
  level:
    com.ikea.warehouse_data_ingestion_service: INFO
    org.springframework.web.multipart: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-}] [%X{operation:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-}] [%X{operation:-}] %logger{50} - %msg%n"
  file:
    name: logs/warehouse-ingestion.log
    max-size: 100MB
    max-history: 10
    total-size-cap: 1GB

