# Kafka Configuration Profile
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic: ${KAFKA_TOPIC:warehouse-events}
  producer:
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    enable-idempotence: true
    max-in-flight-requests-per-connection: 5
  retry:
    attempts: 3
    backoff-delay: 1000
